@url_dev = http://localhost:3000/api/v1

### SignUp
POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: 1234

{
    "name" : "Shop Test",
    "email" : "test09@gmail.com",
    "password" : "123456"
}

